services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"    # HTTP Mapping
      - "5001:443"   # HTTPS Mapping
    depends_on:
      - postgres
    volumes:
      - ./certs:/https:ro
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_HTTPS_PORT: "443"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=GarageGenius;Username=geniusUser;Password=geniusPassword"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "DasIstEinTest123"
      # Wichtig: Kestrel Endpoints überschreiben
      ASPNETCORE_Kestrel__Endpoints__Http__Url: "http://+:80"
      ASPNETCORE_Kestrel__Endpoints__Https__Url: "https://+:443"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: GarageGenius
      POSTGRES_USER: geniusUser
      POSTGRES_PASSWORD: geniusPassword
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U geniusUser -d GarageGenius"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: