// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace GarageGenius.Common.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250714090559_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarageGenius.Common.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.GarageAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchOffice")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("GarageAdmins");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.GarageDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<int>("GarageAdminId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GarageAdminId");

                    b.ToTable("GarageDevices");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.ServiceVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GarageDeviceId")
                        .HasColumnType("integer");

                    b.Property<long>("KmAtVisit")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GarageDeviceId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ServiceVisits");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("ChassisNumber")
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.WorkshopLogEntryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceVisitId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkshopLogEntryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceVisitId");

                    b.ToTable("WorkshopLogEntryImages");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.GarageDevice", b =>
                {
                    b.HasOne("GarageGenius.Common.Models.GarageAdmin", "GarageAdmin")
                        .WithMany("Devices")
                        .HasForeignKey("GarageAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GarageAdmin");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.ServiceVisit", b =>
                {
                    b.HasOne("GarageGenius.Common.Models.Customer", null)
                        .WithMany("Visits")
                        .HasForeignKey("CustomerId");

                    b.HasOne("GarageGenius.Common.Models.GarageDevice", "RecordingDevice")
                        .WithMany("WorkshopLogEntries")
                        .HasForeignKey("GarageDeviceId");

                    b.HasOne("GarageGenius.Common.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordingDevice");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.Vehicle", b =>
                {
                    b.HasOne("GarageGenius.Common.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.WorkshopLogEntryImage", b =>
                {
                    b.HasOne("GarageGenius.Common.Models.ServiceVisit", "ServiceVisit")
                        .WithMany("Images")
                        .HasForeignKey("ServiceVisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceVisit");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.Customer", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.GarageAdmin", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.GarageDevice", b =>
                {
                    b.Navigation("WorkshopLogEntries");
                });

            modelBuilder.Entity("GarageGenius.Common.Models.ServiceVisit", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
